<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
//

// DEPRECATED INCIDENCE TYPES (Without subtypes)
//define('LOCAL_INCIDENCE_REPORT_TYPE_LOGIN', 0);
//define('LOCAL_INCIDENCE_REPORT_TYPE_TECHNICAL', 1);
//define('LOCAL_INCIDENCE_REPORT_TYPE_FUNCTIONAL', 2);
//define('LOCAL_INCIDENCE_REPORT_TYPE_OTHER', 3);

// INCIDENCE TYPES (with subtypes)
define('LOCAL_INCIDENCE_REPORT_FILTER_TYPE_LOGIN', 0);
define('LOCAL_INCIDENCE_REPORT_FILTER_TYPE_SECRETARY', 1);
define('LOCAL_INCIDENCE_REPORT_FILTER_TYPE_PLATFORM', 2);
define('LOCAL_INCIDENCE_REPORT_FILTER_TYPE_COURSE', 3);
define('LOCAL_INCIDENCE_REPORT_FILTER_TYPE_OTHERS', 4);

// INCIDENCE (SUB)TYPES DATA - SECRETARIA ***********************************************

// Incidence (sub)types
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_MATRICULA', 101); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_EXPEDIENTE', 102); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_CONVOCATORIA', 103); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_BAJA', 104); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_ACTAS', 105); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_CERTIFICADOS', 106); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_COMISIONES', 107); // DEPRECATED

// Incidence (sub)type managers
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_MATRICULA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_EXPEDIENTE_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_CONVOCATORIA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_BAJA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_ACTAS_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_CERTIFICADOS_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_COMISIONES_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));

// Incidence (sub)type additional report (* already knows / ! can't identify)
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_MATRICULA_EMAILTO', array(
    // ! LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // ! LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // ! LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_EXPEDIENTE_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_CONVOCATORIA_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_BAJA_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_ACTAS_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_CERTIFICADOS_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_SECRETARIA_COMISIONES_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // ! LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));

// INCIDENCE (SUB)TYPES DATA - PLATAFORMA ***********************************************

// Incidence (sub)types
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_LOGIN', 201);
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CURSO', 202);
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_SECCION', 203); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_FALLO', 204); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_MATRICULA', 205); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_RECURSO', 206); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CONTENIDOS', 207); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CORRECCION', 208); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CALIFICADOR', 209); // DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_ENTREGA', 210); // DEPRECATED

// Incidence (sub)type managers
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_LOGIN_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CURSO_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_SECCION_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_FALLO_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_MATRICULA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_RECURSO_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CONTENIDOS_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CORRECCION_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CALIFICADOR_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_ENTREGA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));

// Incidence (sub)type additional report (* already knows / ! can't identify)
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_LOGIN_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CURSO_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_SECCION_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_FALLO_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_MATRICULA_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_RECURSO_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CONTENIDOS_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CORRECCION_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_CALIFICADOR_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_PLATAFORMA_ENTREGA_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));

// INCIDENCE (SUB)TYPES DATA - CURSOS

// Incidence (sub)types
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_PLAGIO', 301); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CALIFICACION', 302); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXAMEN_FECHA', 303); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXAMEN_LUGAR', 304); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CONVOCATORIA_JE', 305); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXAMEN_RECOGIDA', 306); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ACTAS', 307); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_TAREAS', 308); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ACCESO', 309); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ENTREGAS', 310); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CALIFICACIONES', 311); //DEPRECATED
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_SECCION', 312);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_FALLO', 313);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_MATRICULA', 314);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_RECURSO', 315);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CONTENIDOS', 316);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CORRECCION', 317);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CALIFICADOR', 318);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ENTREGA', 319);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXPEDIENTE', 320);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CONVOCATORIA', 321);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_BAJA', 322);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_FIRMA_ACTAS', 323);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CERTIFICADOS', 324);
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_COMISIONES', 325);

// Incidence (sub)type managers
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_PLAGIO_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CALIFICACION_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXAMEN_FECHA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXAMEN_LUGAR_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CONVOCATORIA_JE_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXAMEN_RECOGIDA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ACTAS_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_TAREAS_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ACCESO_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ENTREGAS_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CALIFICACIONES_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_SECCION_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_FALLO_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_MATRICULA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    //LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_RECURSO_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CONTENIDOS_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CORRECCION_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CALIFICADOR_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ENTREGA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXPEDIENTE_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CONVOCATORIA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_BAJA_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_FIRMA_ACTAS_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CERTIFICADOS_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_COMISIONES_MANAGERS', array(
    // LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    // LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    // LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));

// Incidence (sub)type additional report (* already knows / ! can't identify)
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_PLAGIO_EMAILTO', array(
        // ! LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CALIFICACION_EMAILTO', array(
        // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXAMEN_FECHA_EMAILTO', array(
        // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXAMEN_LUGAR_EMAILTO', array(
        // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        // ! LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CONVOCATORIA_JE_EMAILTO', array(
        //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXAMEN_RECOGIDA_EMAILTO', array(
        //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ACTAS_EMAILTO', array(
        //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_TAREAS_EMAILTO', array(
        // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ACCESO_EMAILTO', array(
        // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ENTREGAS_EMAILTO', array(
        // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CALIFICACIONES_EMAILTO', array(
        // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
        // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
        //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_SECCION_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_FALLO_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_MATRICULA_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_RECURSO_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CONTENIDOS_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CORRECCION_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CALIFICADOR_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_ENTREGA_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_EXPEDIENTE_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CONVOCATORIA_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_BAJA_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_FIRMA_ACTAS_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_CERTIFICADOS_EMAILTO', array(
    // * LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
define('LOCAL_INCIDENCE_REPORT_TYPE_CURSOS_COMISIONES_EMAILTO', array(
    //   LOCAL_INCIDENCE_REPORT_PROFILE_ALUMNO,
    // ! LOCAL_INCIDENCE_REPORT_PROFILE_TUTOR,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_PROFESOR,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_COORDINADOR,
    LOCAL_INCIDENCE_REPORT_PROFILE_JEFATURA,
    // * LOCAL_INCIDENCE_REPORT_PROFILE_SECRETARIA,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_MOODLE,
    //   LOCAL_INCIDENCE_REPORT_PROFILE_FEDERACION,
));
